In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
# Loading CSV

data=pd.read_csv("./Dataset/Churn_Modelling.csv")
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
gender_encoder=LabelEncoder()
data['Gender']=gender_encoder.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
geography_encoder=OneHotEncoder()
encoded_geography=geography_encoder.fit_transform(data[['Geography']])
encoded_geography_df=pd.DataFrame(encoded_geography.toarray(),columns=geography_encoder.get_feature_names_out(['Geography']))
encoded_geography_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [6]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [7]:
data=pd.concat([data.drop('Geography',axis=1),encoded_geography_df],axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [8]:
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [9]:
X_train_full, X_test, y_train_full, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
X_train, X_val, y_train, y_val = train_test_split(
    X_train_full, y_train_full, test_size=0.2, random_state=42
)

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

In [11]:
with open('gender_encoder.pkl','wb') as file:
    pickle.dump(gender_encoder, file)

with open('geography_encoder.pkl','wb') as file:
    pickle.dump(geography_encoder,file)
    
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

#### ANN Regression Problem statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787762709.378705   15947 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1787762710.438315   15947 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787762715.121383   15947 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [13]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

/home/anas/LEARNING/GEN-AI/python/venv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
E0000 00:00:1787762717.686253   15947 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Setting up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Setting up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
# Model Training
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 100266.7500 - mae: 100266.7500 - val_loss: 98607.3516 - val_mae: 98607.3516
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 99848.3594 - mae: 99848.3594 - val_loss: 97751.2734 - val_mae: 97751.2734
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 98333.9766 - mae: 98333.9766 - val_loss: 95479.7500 - val_mae: 95479.7500
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 95193.9297 - mae: 95193.9297 - val_loss: 91440.5234 - val_mae: 91440.5234
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90244.2578 - mae: 90244.2578 - val_loss: 85655.4531 - val_mae: 85655.4531
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 83718.4141 - mae: 83718.4141 - val_loss: 78683.0312 - val_mae: 78683.0312
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 76310.9844 - mae: 76310.9844 - val_loss: 71417.2812 - val_mae: 71417.2812
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 68892.3438 - mae: 68892.3438 - val_loss: 64629.9688 - val_mae: 64629.9688
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 62282.6562 - mae: 62282.6562 - val_loss: 58977.2969 - val_mae: 58977.2969
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57199.9062 - mae: 57199.9062 - val_loss: 54967.3398 - val_mae: 54967.3398
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53815.5469 - mae: 53815.5469 - val_loss: 52588.1094 - val_mae: 52588.1094
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 51939.4648 - mae: 51939.4648 - val_loss: 51441.0898 - val_mae: 51441.0898
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50980.9219 - mae: 50980.9219 - val_loss: 50959.7578 - val_mae: 50959.7578
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50521.5000 - mae: 50521.5000 - val_loss: 50757.6484 - val_mae: 50757.6484
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50278.7305 - mae: 50278.7305 - val_loss: 50660.8438 - val_mae: 50660.8438
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50162.9414 - mae: 50162.9414 - val_loss: 50624.7773 - val_mae: 50624.7773
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 50102.7383 - mae: 50102.7383 - val_loss: 50594.3008 - val_mae: 50594.3008
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50056.7109 - mae: 50056.7109 - val_loss: 50575.9062 - val_mae: 50575.9062
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50012.5703 - mae: 50012.5703 - val_loss: 50554.8711 - val_mae: 50554.8711
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 49974.9141 - mae: 49974.9141 - val_loss: 50536.8516 - val_mae: 50536.8516
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49943.3984 - mae: 49943.3984 - val_loss: 50515.6133 - val_mae: 50515.6133
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49915.0781 - mae: 49915.0781 - val_loss: 50499.3516 - val_mae: 50499.3516
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49889.7812 - mae: 49889.7812 - val_loss: 50480.0469 - val_mae: 50480.0469
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49865.6289 - mae: 49865.6289 - val_loss: 50468.0703 - val_mae: 50468.0703
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49845.2734 - mae: 49845.2734 - val_loss: 50454.7031 - val_mae: 50454.7031
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49825.0508 - mae: 49825.0508 - val_loss: 50441.2188 - val_mae: 50441.2188
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49804.7695 - mae: 49804.7695 - val_loss: 50436.3086 - val_mae: 50436.3086
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49786.9219 - mae: 49786.9219 - val_loss: 50428.8242 - val_mae: 50428.8242
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49768.8633 - mae: 49768.8633 - val_loss: 50418.4492 - val_mae: 50418.4492
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 49751.1914 - mae: 49751.1914 - val_loss: 50412.3828 - val_mae: 50412.3828
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49738.6445 - mae: 49738.6445 - val_loss: 50401.3945 - val_mae: 50401.3945
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49724.1016 - mae: 49724.1016 - val_loss: 50403.9805 - val_mae: 50403.9805
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 49704.4883 - mae: 49704.4883 - val_loss: 50390.1211 - val_mae: 50390.1211
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49694.6445 - mae: 49694.6445 - val_loss: 50386.3516 - val_mae: 50386.3516
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49681.0859 - mae: 49681.0859 - val_loss: 50377.0352 - val_mae: 50377.0352
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49666.7383 - mae: 49666.7383 - val_loss: 50376.8320 - val_mae: 50376.8320
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49654.2969 - mae: 49654.2969 - val_loss: 50372.0547 - val_mae: 50372.0547
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49646.3711 - mae: 49646.3711 - val_loss: 50375.7852 - val_mae: 50375.7852
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49635.6094 - mae: 49635.6094 - val_loss: 50365.9609 - val_mae: 50365.9609
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49624.5664 - mae: 49624.5664 - val_loss: 50367.2188 - val_mae: 50367.2188
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49611.6055 - mae: 49611.6055 - val_loss: 50362.3125 - val_mae: 50362.3125
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49601.7305 - mae: 49601.7305 - val_loss: 50364.5547 - val_mae: 50364.5547
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 49590.0703 - mae: 49590.0703 - val_loss: 50359.5508 - val_mae: 50359.5508
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49579.9297 - mae: 49579.9297 - val_loss: 50360.1055 - val_mae: 50360.1055
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49570.5312 - mae: 49570.5312 - val_loss: 50357.0273 - val_mae: 50357.0273
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 49564.8008 - mae: 49564.8008 - val_loss: 50361.3555 - val_mae: 50361.3555
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49555.0234 - mae: 49555.0234 - val_loss: 50366.7148 - val_mae: 50366.7148
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49547.6914 - mae: 49547.6914 - val_loss: 50360.0234 - val_mae: 50360.0234
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 49537.3359 - mae: 49537.3359 - val_loss: 50359.3047 - val_mae: 50359.3047
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 49531.2148 - mae: 49531.2148 - val_loss: 50361.5273 - val_mae: 50361.5273
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 49521.6562 - mae: 49521.6562 - val_loss: 50360.1523 - val_mae: 50360.1523
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49513.4766 - mae: 49513.4766 - val_loss: 50361.5977 - val_mae: 50361.5977
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49508.3086 - mae: 49508.3086 - val_loss: 50359.3672 - val_mae: 50359.3672
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49500.0898 - mae: 49500.0898 - val_loss: 50365.6602 - val_mae: 50365.6602
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49491.7969 - mae: 49491.7969 - val_loss: 50367.3906 - val_mae: 50367.3906

In [17]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [18]:
# Load Tensorflow extension

# Source - https://stackoverflow.com/a/55970819
# Posted by Vlad, modified by community. See post 'Timeline' for change history
# Retrieved 2026-05-15, License - CC BY-SA 4.0

%load_ext tensorboard

In [19]:
%tensorboard --logdir logs/fit/20260826-214519