In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle
from tensorflow.keras.models import load_model

In [22]:
# Load all th trained model,scalar pickel, onehot
model=load_model('model.h5')

# load encoder and scalar
with open("gender_encoder.pkl",'rb') as file:
    gender_encoder=pickle.load(file)

with open("geography_encoder.pkl",'rb') as file:
    geography_encoder=pickle.load(file)
    
with open("scaler.pkl",'rb') as file:
    scalar=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [23]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'Exited': 0
}

In [24]:
geo_encoded=geography_encoder.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=geography_encoder.get_feature_names_out(['Geography']))
geo_encoded_df

/home/anas/LEARNING/GEN-AI/python/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [25]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited
0,600,France,Male,40,3,60000,2,1,1,0

In [26]:
# Encode the categorical cols
input_df['Gender']=gender_encoder.transform([input_df['Gender']])

/home/anas/LEARNING/GEN-AI/python/venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [ ]:
input_df = pd.concat([input_df.drop("Geography", axis=1),geo_encoded_df], axis=1)

In [28]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,0,1.0,0.0,0.0

In [29]:
expected_columns = [
    "CreditScore",
    "Gender",
    "Age",
    "Tenure",
    "Balance",
    "NumOfProducts",
    "HasCrCard",
    "IsActiveMember",
    "Exited",
    "Geography_France",
    "Geography_Germany",
    "Geography_Spain"
]

input_df = input_df[expected_columns]


print("\nProcessed Input:")
print(input_df)

Processed Input:
   CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       1   40       3    60000              2          1

   IsActiveMember  Exited  Geography_France  Geography_Germany  \
0               1       0               1.0                0.0

   Geography_Spain
0              0.0

In [30]:
scalaer_input=scalar.transform(input_df)
scalaer_input

array([[-0.53407719,  0.91659043,  0.10147008, -0.6884294 , -0.25975097,
         0.80255152,  0.65075921,  0.96861719, -0.50901764,  0.99439073,
        -0.58047761, -0.56989252]])

In [31]:
prediction=model.predict(scalaer_input)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step

array([[87697.41]], dtype=float32)

In [33]:
predicted_salary = prediction[0][0]
predicted_salary

np.float32(87697.41)

In [34]:
print("ESTIMATED SALARY PREDICTION")
print(f"Predicted Estimated Salary: {predicted_salary:.2f}")

ESTIMATED SALARY PREDICTION
Predicted Estimated Salary: 87697.41