In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787678459.439278  122714 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1787678459.570130  122714 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787678463.742107  122714 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [2]:
# Load all th trained model,scalar pickel, onehot
model=load_model('model.h5')

# load encoder and scalar
with open("onehot_encoder_geography.pkl",'rb') as file:
    label_encoder_geo=pickle.load(file)

with open("label_encoder_gender.pkl",'rb') as file:
    label_encoder_gender=pickle.load(file)
    
with open("scaler.pkl",'rb') as file:
    scalar=pickle.load(file)

E0000 00:00:1787678469.079327  122714 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [4]:
geo_encoded=label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

/home/anas/LEARNING/GEN-AI/python/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [5]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [6]:
# Encode the categorical cols
input_df['Gender']=label_encoder_gender.transform([input_df['Gender']])

/home/anas/LEARNING/GEN-AI/python/venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [7]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [8]:
# ## concatination one hot encoded 
input_df=pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [9]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [10]:
scalaer_input=scalar.transform(input_df)
scalaer_input

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [11]:
prediction=model.predict(scalaer_input)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step

array([[0.0479814]], dtype=float32)

In [12]:
prediction_probability=prediction[0][0]
prediction_probability

np.float32(0.047981404)

In [13]:
if prediction_probability > 0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is not likely to churn.")

The customer is not likely to churn.